### ISSUE TITLE
Please create new script for tracking imports over time by user

### ISSUE THREAD

**Issue by ghost** [sorgerlab/OMERO_scripts#21]
I am creating this issue to memorialize what we discussed yesterday. We need a script which queries the OMERO database for a list of all imports in a given date range. For now we will ignore whether the imports are plates or datasets. The goal is to be able to produce a graph showing cumulative growth in the number of images in the HMS OMERO server over time either for a user or for all users. The time resolution of this graph should be at most a week and at least a day. It would be nice to have date range and user as input parameters. Group would be nice too, but let's save that for a follow up version.

**Comment by dpwrussell** [comment]
Resolved by #22
